server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zimrancis/microservices-config-store          
          #username: root
          #passphrase: 12345  
          search-paths:
          - 'service-config/*service'
          #repos:            
          #username: root
          #passphrase: 12345
